package bg.BulgariaTripPlanner.model.enums;

public enum Made {
    Abbotsfar("Abbotsfar"),
    AbeStar("AbeStar"),
    Abra("Abra"),
    Acabion("Acabion"),
    AccessMotors("Access Motors"),
    AceMotorCorporation("Ace Motor Corporation"),
    Adiva("Adiva"),
    Adler("Adler"),
    AdlyMoto("Adly Moto"),
    Aeon("Aeon"),
    Aermacchi("Aermacchi"),
    AgratiGarelli("Agrati Garelli"),
    AJP("AJP"),
    AJS("AJS"),
    AKTMotos("AKT Motos"),
    Alfer("Alfer"),
    AlligatorMotorcycleCompany("Alligator Motorcycle Company"),
    Allstate("Allstate"),
    Aprilia("Aprilia"),
    AtlasHonda("Atlas Honda"),
    APHonda("A.P. Honda"),
    ArielMotorCompany("Ariel Motor Company"),
    ArchMotorcycle("Arch Motorcycle"),
    ATKMotorcycles("ATK Motorcycles"),
    Agrale("Agrele"),
    AGF("AGF"),
    Alcyon("Alcyon"),
    Automoto("Automoto"),
    Ardie("Ardie"),
    AltaAndhraPradeshScootersLimited("Alta Andhra Pradesh Scooters Limited"),
    API("API"),
    Aeromere("Aeromere"),
    Autozodiaco("Autozodiaco"),
    AlexanderLeutnerCo("Alexander Leutner & Co."),
    AJWMotorcycles("AJW Motorcycles"),
    AmbassadorMotorcycles("Ambassador Motorcycles"),
    AssociatedMotorCycles("Associated Motor Cycles"),
    Armstrong("Armstrong"),
    AmericanIronHorse("American IronHorse"),
    BrasilMovimento("Brasil & Movimento"),
    BombardierRecreationalProducts("Bombardier Recreational Products"),
    BaotianMotorcycleCompany("Baotian Motorcycle Company"),
    Blata("Blata"),
    BMWMotorrad("BMW Motorrad"),
    BajajAuto("Bajaj Auto"),
    Benelli("Benelli"),
    BetaMotor("Beta Motor"),
    Bimota("Bimota"),
    Bultaco("Bultaco"),
    BossHossCycles("Boss Hoss Cycles"),
    BrammoInc("Brammo Inc."),
    BennettBarkellMotorcycles("Bennett & Barkell Motorcycles"),
    BrumanaPugliese("Brumana Pugliese"),
    Balkan("Balkan"),
    Böhmerland("Böhmerland"),
    BMW("BMW"),
    Bianchi("Bianchi"),
    BeardmorePrecision("Beardmore Precision"),
    Blackburne("Blackburne"),
    BroughMotorcycles("Brough Motorcycles"),
    BroughSuperior("Brough Superior"),
    BSACompany("BSA Company"),
    BuellMotorcycleCompany("Buell Motorcycle Company"),
    BrittenMotorcycleCompany("Britten Motorcycle Company"),
    CanAmMotorcycles("Can-Am Motorcycles"),
    ChangJiang("Chang Jiang"),
    ČeskáZbrojovkaStrakonice("Česká zbrojovka Strakonice"),
    Cagiva("Cagiva"),
    Carabela("Carabela"),
    Casal("Casal"),
    CheneyRacing("Cheney Racing"),
    ClewsCompetitionMotorcycles("Clews Competition Motorcycles"),
    ClevelandCycleWerks("Cleveland CycleWerks"),
    ConfederateMotors("Confederate Motors"),
    Ceccato("Ceccato"),
    Cimatti("Cimatti"),
    Cooper("Cooper"),
    CentralneWarsztatySamochodowe("Centralne Warsztaty Samochodowe"),
    CalthorpeMotorCompany("Calthorpe Motor Company"),
    Clyno("Clyno"),
    CottonMotorCompany("Cotton Motor Company"),
    CoventryEagleCrockerMotorcycleCompany("Coventry-Eagle Crocker Motorcycle Company"),
    Cushman("Cushman"),
    DafraMotos("Dafra Motos"),
    Dayun("Dayun"),
    DucatiMotorHoldingSPA("Ducati Motor Holding S.p.A."),
    DYLMotorcycles("DYL Motorcycles"),
    Derbi("Derbi"),
    DeltaGnom("Delta-Gnom"),
    Dollar("Dollar"),
    DRad("D-Rad"),
    DKW("DKW"),
    DellaFerrera("Della Ferrera"),
    DotCycleAndMotorManufacturingCompany("Dot Cycle and Motor Manufacturing Company"),
    Douglas("Douglas"),
    Dnepr("Dnepr"),
    Dresch("Dresch"),
    DaelimMotorCompany("Daelim Motor Company"),
    EvokeMotorcycles("Evoke Motorcycles"),
    EnergicaMotorCompany("Energica Motor Company"),
    ElectricMotorCorporation("Electric Motor Corporation"),
    ErikBuellRacing("Erik Buell Racing"),
    Eso("Eso"),
    ExpressWerke("Express Werke"),
    EscortsGroup("Escorts Group"),
    EisenacherMotorenwerk("Eisenacher Motorenwerk"),
    EMCMotorcycles("EMC Motorcycles"),
    ExcelsiorMotorCompany("Excelsior Motor Company"),
    ExcelsiorMotorManufacturingSupplyCompany("Excelsior Motor Manufacturing & Supply Company"),
    ExcelsiorHendersonMotorcycle("Excelsior-Henderson Motorcycle"),
    FanticMotor("Fantic Motor"),
    FN("FN"),
    FBMondial("FB Mondial"),
    Frera("Frera"),
    Fusi("Fusi"),
    FAMEL("FAMEL"),
    FrancisBarnettFischerMotorCompany("Francis-Barnett Fischer Motor Company"),
    FlyingMerkel("Flying Merkel"),
    GhezziBrian("Ghezzi & Brian"),
    Gilera("Gilera"),
    GasGas("Gas Gas"),
    Greeves("Greeves"),
    GilletHerstal("Gillet Herstal"),
    GIMAGnomeEtRhône("GIMA Gnome et Rhône"),
    Galbusera("Galbusera"),
    GarelliMotorcycles("Garelli Motorcycles"),
    Gimson("Gimson"),
    GorkyMotorcyclePlant("Gorky Motorcycle Plant"),
    HunterMotorcycles("Hunter Motorcycles"),
    HusqvarnaMotorcycles("Husqvarna Motorcycles"),
    HeroMotoCorp("Hero MotoCorp"),
    Horex("Horex"),
    HarleyDavidson("Harley-Davidson"),
    HarleyDavidsonIndia("Harley-Davidson India"),
    Honda("Honda"),
    HondaMotorcycleAndScooterIndia("Honda Motorcycle and Scooter India"),
    HondaMotorcycleThailand("Honda Motorcycle Thailand"),
    HeskethMotorcycles("Hesketh Motorcycles"),
    Hecker("Hecker"),
    Hercules("Hercules"),
    Hodaka("Hodaka"),
    Husaberg("Husaberg"),
    Haden("Haden"),
    HRDMotorcycles("HRD Motorcycles"),
    HendersonMotorcycle("Henderson Motorcycle"),
    HelkamaHildebrandWolfmüller("Helkama Hildebrand & Wolfmüller"),
    Hoffmann("Hoffmann"),
    ItaljetI("Italjet I"),
    talika("talika"),
    IMZUral("IMZ-Ural"),
    IZh("IZh"),
    IndianMotocycleManufacturingCompany("Indian Motocycle Manufacturing Company"),
    IdealJawa("Ideal Jawa"),
    Innocenti("Innocenti"),
    Iso("Iso"),
    Ivy("Ivy"),
    JamunaMotorcycles("Jamuna Motorcycles"),
    JinchengSuzuki("Jincheng Suzuki"),
    JAWAMoto("JAWA Moto"),
    Junak("Junak"),
    JanusMotorcycles("Janus Motorcycles"),
    Juery("Juery"),
    JamesCycleCo("James Cycle Co"),
    JinanQingqi("Jinan Qingqi"),
    JAPrestwichIndustries("JA Prestwich Industries"),
    KawasakiHeavyIndustriesMotorcycleEngine("Kawasaki Heavy Industries Motorcycle & Engine"),
    KTM("KTM"),
    KTMAsiaMotorcycleManufacturing("KTM Asia Motorcycle Manufacturing"),
    Kymco("Kymco"),
    KillingerAndFreundMotorcycle("Killinger and Freund Motorcycle"),
    Kreidler("Kreidler"),
    KineticEngineeringLimited("Kinetic Engineering Limited"),
    LandElectricMotorcycle("Land Electric Motorcycle"),
    Lifan("Lifan"),
    LoncinHoldings("Loncin Holdings"),
    LightningMotorcycle("Lightning Motorcycle"),
    LaurinKlement("Laurin & Klement"),
    Lefas("Lefas"),
    Lamborghini("Lamborghin"),
    Lambretta("Lambretta"),
    Laverda("Laverda"),
    LubeMotorcycles("Lube Motorcycles"),
    Levis("Levis"),
    Motomel("Motomel"),
    Minsk("Minsk"),
    Midual("Midual"),
    MahindraTwoWheelers("Mahindra Two Wheelers"),
    MotoGuzzi("Moto Guzzi"),
    MVAgusta("MV Agusta"),
    Malaguti("Malaguti"),
    Minarelli("Minarelli"),
    MotoMorini("Moto Morini"),
    Modenas("Modenas"),
    MontesaHonda("Montesa Honda"),
    Mondial("Mondial"),
    MegelliMotorcycles("Megelli Motorcycles"),
    MétisseMotorcycles("Métisse Motorcycles"),
    MotoCzysz("MotoCzysz"),
    MarineTurbineTechnologies("Marine Turbine Technologies"),
    Minerva("Minerva"),
    Motobécane("Motobécane"),
    MonetGoyon("Monet-Goyon"),
    Maico("Maico"),
    Mars("Mars"),
    Megola("Megola"),
    Münch("Münch"),
    MopedsIndiaLimited("Mopeds India Limited"),
    Malanca("Malanca"),
    MAS("MAS"),
    Maserati("Maserati"),
    Morbidelli("Morbidelli"),
    MorettiMotorCompany("Moretti Motor Company"),
    MotoRumi("MotoRumi"),
    Motobi("Motobi"),
    Marusho("Marusho"),
    Meguro("Meguro"),
    MitsubishiSilverPigeon("Mitsubishi Silver Pigeon"),
    Miyata("Miyata"),
    MotoTrans("MotoTrans"),
    Monark("Monark"),
    Martinsyde("Martinsyde"),
    Matchless("Matchless"),
    Mustang("Mustang"),
    MoscowMotorcyclePlant("Moscow Motorcycle Plant"),
    MZMotorradundZweiradwerk("MZ Motorrad- und Zweiradwerk"),
    Maratos("Maratos"),
    MEBEA("MEBEA"),
    Mego("Mego"),
    NortonMotorcycleCompany("Norton Motorcycle Company"),
    Naza("Naza"),
    Nimbus("Nimbus"),
    NewMap("New-Map"),
    Nougier("Nougier"),
    Neander("Neander"),
    NSUMotorenwerke("NSU Motorenwerke"),
    NerACar("Ner-A-Car"),
    NewHudsonMotorcycles("New Hudson Motorcycles"),
    NewImperialMotors("New Imperial Motors"),
    NormanCycles("Norman Cycles"),
    NATI("NATI"),
    Ossa("Ossa"),
    Opel("Opel"),
    Orionette("Orionette"),
    OsbornEngineeringCompany("Osborn Engineering Company"),
    OKSupreme("OK-Supreme"),
    PHPAutomobiles("PHP Automobiles"),
    PeugeotMotocycles("Peugeot Motocycles"),
    Paton("Paton"),
    Piaggio("Piaggio"),
    PakSuzukiMotors("Pak Suzuki Motors"),
    PGOScooters("PGO Scooters"),
    Puch("Puch"),
    Praga("Praga"),
    PremierMotorcycles("Premier Motorcycles"),
    PhelonMoore("Phelon & Moore"),
    Penton("Penton"),
    PierceArrowMotorCarCompany("Pierce-Arrow Motor Car Company"),
    PopeManufacturingCompany("Pope Manufacturing Company"),
    PodolskMechanicalPlant("Podolsk Mechanical Plant"),
    QianjiangMotorcycle("Qianjiang Motorcycle"),
    Quadrant("Quadrant"),
    Quasar("Quasar"),
    RunnerAutomobiles("Runner Automobiles"),
    RoyalEnfield("Royal Enfield"),
    RaviMotorcycles("Ravi Motorcycles"),
    Rokon("Rokon"),
    Ratier("Ratier"),
    RikuoMotorcycle("Rikuo Motorcycle"),
    RaleighBicycleCompany("Raleigh Bicycle Company"),
    RickmanMotorcycles("Rickman Motorcycles"),
    RudgeWhitworth("Rudge-Whitworth"),
    RidleyMotorcycleCompany("Ridley Motorcycle Company"),
    RoehrMotorcycleCompany("Roehr Motorcycle Company"),
    Rieju("Rieju"),
    Siambretta("Siambretta"),
    SolInvictusMotorcycleCo("Sol Invictus Motorcycle Co."),
    Scorpa("Scorpa"),
    Sherco("Sherco"),
    Silk("Silk"),
    SuzukiMotorcycleIndiaLimited("Suzuki Motorcycle India Limited"),
    SuzukiIndomobilMotor("Suzuki Indomobil Motor"),
    SWM("SWM"),
    Suzuki("Suzuki"),
    SYMMotors("SYM Motors"),
    SFM("SFM"),
    Sanglas("Sanglas"),
    Saroléa("Saroléa"),
    Simson("Simson"),
    Santamaria("Santamaria"),
    SHL("SHL"),
    SIS("SIS"),
    ScottMotorcycleCompany("Scott Motorcycle Company"),
    SingerMotors("Singer Motors"),
    Sprite("Sprite"),
    StevensMotorcycles("Stevens Motorcycles"),
    Sun("Sun"),
    SunbeamCycles("Sunbeam Cycles"),
    SimplexManufacturingCorporation("Simplex Manufacturing Corporation"),
    Sokół("Sokół"),
    SachsMotorcycles("Sachs Motorcycles"),
    Tehuelche("Tehuelche"),
    Thumpstar("Thumpstar"),
    Terrot("Terrot"),
    TriumphMotorcyclesLtd("Triumph Motorcycles Ltd"),
    TVSMotorCompany("TVS Motor Company"),
    TerraModena("Terra Modena"),
    TaiwanGoldenBee("Taiwan Golden Bee"),
    Tunturi("Tunturi"),
    Triumph("Triumph (TWN)"),
    Tohatsu("Tohatsu"),
    Tempo("Tempo"),
    TandonMotorcycles("Tandon Motorcycles"),
    TriumphEngineering("Triumph Engineering"),
    Thor("Thor"),
    TitanMotorcycleCompany("Titan Motorcycle Company"),
    TIZ("TIZ"),
    UnitedAutoIndustries("United Auto Industries"),
    USHighland("US Highland"),
    VoxanVespaVyrusVelomotors("Voxan Vespa Vyrus Velomotors"),
    VoskhodVictoriaVelocette("Voskhod Victoria Velocette"),
    VilliersEngineering("Villiers Engineering"),
    VincentMotorcycles("Vincent Motorcycles"),
    VictoryMotorcycles("Victory Motorcycles"),
    YinxiangMotorcycle("Yinxiang Motorcycle"),
    YamahaMotorCompany("Yamaha Motor Company"),
    YamahaMotorPakistanYMC("Yamaha Motor Pakistan YMC"),
    Yankee("Yankee"),
    Zanella("Zanella"),
    Znen("Znen"),
    Zongshen("Zongshen"),
    ZElectricVehicle("Z Electric Vehicle"),
    ZeroMotorcycles("Zero Motorcycles"),
    Zündapp("Zündapp"),
    ZenithMotorcycles("Zenith Motorcycles");
    private String value;

    private Made(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }
}
